# Generated by Django 6.0.1 on 2026-02-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.IntegerField()),
                ('productDescription', models.TextField()),
                ('productStock', models.PositiveIntegerField()),
                ('productColor', models.CharField(max_length=20, null=True)),
                ('productStatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentAge', models.IntegerField()),
                ('studentCity', models.CharField(max_length=40)),
                ('studentEmail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
